### ISSUE TITLE
Change Steam OS logo to look more like the official one

### ISSUE THREAD

**Issue by MartinLeGrand** [r-PlaceTux/overlay#5]
![IMG_20220401_202516](https://user-images.githubusercontent.com/57072480/161378867-7fb5a0ab-245a-493f-807d-36695f10eb59.jpg)
![pixil-frame-0(2)](https://user-images.githubusercontent.com/57072480/161378871-e53779b2-ecbc-4ebe-9ba2-f88b2785fd40.png)
Remove four pixels at the rim, and make it thicker at the corners.

The semi circle is only supposed to go half way.

**Comment by Epikest** [comment]
tux design is currently final, however this issue will be reopened when needed

**Comment by Epikest** [comment]
https://github.com/r-PlaceTux/Overlay/commit/6a50359310128f28cef1582b8e6c726684cba9cd
